# Generated by Django 3.1.5 on 2021-01-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alunos',
            fields=[
                ('name', models.CharField(max_length=70)),
                ('age', models.DateField()),
                ('RA', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('dig_ra', models.CharField(max_length=1)),
                ('serie', models.CharField(max_length=1)),
                ('turma', models.CharField(max_length=1)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='cadastro_photos')),
            ],
        ),
    ]
