# Generated by Django 3.1.5 on 2021-01-06 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reuniao', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='alunos',
            new_name='reuniao',
        ),
    ]
