# Generated by Django 3.1.5 on 2021-01-07 00:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniao', '0002_auto_20210106_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reuniao',
            old_name='dig_ra',
            new_name='dig_RA',
        ),
        migrations.RenameField(
            model_name='reuniao',
            old_name='age',
            new_name='nascimento',
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='RA',
            field=models.IntegerField(max_length=9, primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9)]),
        ),
    ]
