# Generated by Django 3.1.5 on 2021-01-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniao', '0003_auto_20210106_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='RA',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
