# Generated by Django 3.1.5 on 2021-01-10 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reuniao', '0004_auto_20210109_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reuniao',
            old_name='RA',
            new_name='id',
        ),
    ]
