# Generated by Django 3.1.5 on 2021-01-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniao', '0007_reuniao_presenca'),
    ]

    operations = [
        migrations.AddField(
            model_name='reuniao',
            name='tutor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='nascimento',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
