# Generated by Django 3.1.5 on 2021-01-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniao', '0008_auto_20210115_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='presenca',
            field=models.CharField(choices=[('presenca', 'Presente'), ('ausente', 'Ausente')], max_length=8),
        ),
    ]
