# Generated by Django 3.1.5 on 2021-01-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniao', '0010_auto_20210117_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reuniao',
            name='presenca',
        ),
        migrations.AddField(
            model_name='reuniao',
            name='ausente',
            field=models.CharField(blank=True, choices=[('presente', 'Presente'), ('ausente', 'Ausente')], max_length=8, null=True),
        ),
    ]
