# Generated by Django 3.1.5 on 2021-01-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniao', '0012_auto_20210117_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='ausente',
            field=models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente')], default='ausente', max_length=8, null=True),
        ),
    ]
