# Generated by Django 3.1.5 on 2021-01-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniao', '0013_auto_20210117_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
