# Generated by Django 3.1.5 on 2021-01-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniao', '0014_auto_20210118_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
