# Generated by Django 3.1.5 on 2021-01-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniao', '0015_auto_20210124_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='nascimento',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
