# Generated by Django 3.1.5 on 2021-01-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniao', '0016_auto_20210126_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
